import Banner from "@/components/Banner/Banner";
import StateSection from "@/components/StateSection/StateSection";
import TrendingApps from "@/components/TrendingApps/TrendingApps";

export const metadata = {
  title: "Home || Salman",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="">
      <main className="">
        <Banner></Banner>
        <StateSection></StateSection>
        <TrendingApps></TrendingApps>
        
        
      </main>
    </div>
  );
}
